name: peerstream
description: "A legal peer-to-peer video streaming college project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0-192.0.dev

dependencies:
  dartnative: ^1.0.0
  dartnative_ios: ^1.0.0
  dartnative_android: ^1.0.0
  dartnative_shared_preferences: ^1.0.0
  dartnative_path_provider: ^1.0.0
  dartnative_video_player: ^1.0.0
  dio: ^5.11.1
  crypto: ^3.0.7
  ffi: ^2.1.0
  libtorrent_flutter:
    path: packages/libtorrent_flutter

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0

dartnative:
  assets:
    - assets/dn-logo.png
    - assets/cacert.pem
